[project]
name = "reptilia"
version = "0.1.0"
description = "SystemVerilog RISC-V implementation and libraries"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "colorama>=0.4.6",
    "ninja>=1.13",
]

[tool.uv]
package = false

[tool.ruff]
extend-exclude = ["riscv-tests"]

[dependency-groups]
dev = [
    "types-colorama>=0.4.15.20250801",
]
